Create verificar-compra
bryamgh123/boton-pagos pull request #5
Opened 2022-10-24 23:53 UTC by bryamgh123

verificar-compra #compra verificada y total

2022-10-24 23:58 UTC, CrisPesantez requested changes

2022-10-24 23:58 UTC, CrisPesantez commented on verificar-compra
> +#compra verificada
poner negrita y titulo

2022-10-24 23:59 UTC, bryamgh123 commented on verificar-compra
> +#compra verificada
no

2022-10-25 00:02 UTC, bryamgh123 reviewed
ya

2022-10-25 00:03 UTC, CrisPesantez commented
no esta niño tontis

2022-10-25 00:04 UTC, CrisPesantez approved these changes

2022-10-25 00:04 UTC, merged